"""empty message

Revision ID: 1d1cabe0f58e
Revises: cb7a97697b00
Create Date: 2020-08-17 19:09:51.537133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1cabe0f58e'
down_revision = 'cb7a97697b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('show_Venue_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('show', 'Venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_Venue_id_fkey', 'show', 'Venue', ['Venue_id'], ['id'])
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###
