"""empty message

Revision ID: 8c22ca5d2b01
Revises: 40dea8107299
Create Date: 2020-08-17 20:03:31.370754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c22ca5d2b01'
down_revision = '40dea8107299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'area_id')
    # ### end Alembic commands ###
