"""empty message

Revision ID: cb7a97697b00
Revises: f522b341a44a
Create Date: 2020-08-17 19:09:23.872112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7a97697b00'
down_revision = 'f522b341a44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('Venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'show', 'Venue', ['Venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'Venue_id')
    # ### end Alembic commands ###
